language: python
matrix:
    include:
        - python: 2.7
          dist: trusty
          sudo: false
        - python: 3.6
          dist: trusty
          sudo: false
        - python: 3.7
          dist: xenial
          sudo: true

install:
  - pip install --upgrade pip setuptools wheel
  - pip install --only-binary=numpy,scipy numpy scipy
  - pip install networkx
  - pip install xlrd
  - pip install pandas
  - pip install shapely
  - pip install pyproj
  - pip install uesgraphs
  - pip install -e git+https://github.com/RWTH-EBC/richardsonpy.git#egg=richardsonpy
  - pip install -e .
  - pip install pytest-cov
  - pip install coveralls
  - pip install flake8

script:
  - py.test

after_success:
  - coveralls
